### ISSUE TITLE
JetBrains is openly supporting Ukraine

### ISSUE THREAD

**Issue by iluuu1994** [vshymanskyy/StandWithUkraine#11] opened 2022-03-07 13:18 UTC
JetBrains openly supports Ukraine and condemns the war. They also have employees located in the Ukraine.

https://twitter.com/jetbrains/status/1496786254494670851

![image](https://user-images.githubusercontent.com/1752683/157040267-d122baab-dad5-4dcd-8636-d632a30b424e.png)

Their CEO (who is Russian) is also openly condemning the war.

https://twitter.com/mshafirov/status/1496129482993897493

![image](https://user-images.githubusercontent.com/1752683/157040387-22cc9104-d7f6-458b-9336-9811f2efae87.png)

JetBrains' headquarters are also in the Czech Republic, not in Russia.

https://en.wikipedia.org/wiki/JetBrains

![image](https://user-images.githubusercontent.com/1752683/157040169-d5da608f-9fd6-4775-8f39-030591ce2b6d.png)

I don't think it's fair to punish somebody who openly condemns their governments actions. They are not responsible for the war, Putin is. The same goes for anybody on [this list](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/Boycott.md), IMO they should be considered innocent until proven guilty. Yes, not buying these products has a small effect on Russias economy, negligible for Putin, but significant for the developers.

**Comment by vshymanskyy** [comment] 2022-03-07 14:52
How about their offices? They continue paying taxes in Russia, sponsoring the war.
Is there any official announcement addressing that?
https://www.jetbrains.com/company/contacts/
![image](https://user-images.githubusercontent.com/1506708/157057110-ba648a21-23e0-4237-988b-6a8ae3ec42d7.png)

**Comment by azjezz** [comment] 2022-03-07 14:55
Are you suggesting firing everyone in Russia, and closing the offices?

**Comment by iluuu1994** [comment] 2022-03-07 15:01
> They continue paying taxes in Russia, sponsoring the war.

Sadly, yes. But I don't believe that even if we stopped buying every product of every company on that list it would make a measurable different to Putin. But it would obviously ruin those companies. Sanctions need to be imposed on big systems like oil and gas.

**Comment by vshymanskyy** [comment] 2022-03-07 15:03
I agree, in general.
Ukrainian OSS community is currently discussing how to deal with such requests. Please hold on.

**Comment by azjezz** [comment] 2022-03-07 15:03
The only way not to pay taxes to Russian government would be to close the Russian branch, meaning firing everyone that works there, or forcing employees to relocate to another country, leaving their families and loved ones behind.

just because someone is born and raised in Russia, it doesn't make them a bad person, and saying that every company with a Russian branch ( as a mentioned in #13 - this includes Microsoft, Google, Facebook, F5/Nginx .. and much more ) needs to be closed ( closing offices and sending people home, means you still need to pay taxes ), is not a real solution.

**Comment by vshymanskyy** [comment] 2022-03-07 15:06
Is there any evidence of JetBrains officially donating / supporting financially the Ukraine?

**Comment by iluuu1994** [comment] 2022-03-07 15:09
@vshymanskyy Thanks for considering!

> Is there any evidence of JetBrains officially donating to the Ukraine (or otherwise supporting financially)?

Just that they have employees from Ukraine (which depend on their financial stability more than ever), but I'm unaware of other donations (I'm not part of JetBrains).

**Comment by azjezz** [comment] 2022-03-07 15:11
another important note:  when buying a product, you are paying JetBrains ( Czech ), not JetBrains Russia, AFAIK, JetBrains Russia branch doesn't produce it's own products, meaning the only money going to Russia via JetBrains, is the employees salary+taxes, which would be the same regardless of whether people are buying the products or not.

**Comment by vshymanskyy** [comment] 2022-03-07 15:16
> > Is there any evidence of JetBrains officially donating to the Ukraine (or otherwise supporting financially)?
> 
> Just that they have employees from Ukraine (who depend on their financial stability more than ever), but I'm unaware of other donations (I'm not part of JetBrains).

@iluuu1994 can you find any Ukraine offices here: https://www.jetbrains.com/company/contacts/ ?

**Comment by azjezz** [comment] 2022-03-07 15:17
They have Ukrainian employees, no office in Ukraine.

**Comment by azjezz** [comment] 2022-03-07 15:19
> Sorry, condemning war is not going to stop it.

Yes, but neither is not buying a product from a company that is not Russian, as i stated, the same amount of money will be going to Russia whether the product is sold or not.

**Comment by webknjaz** [comment] 2022-03-07 15:26
> which would be the same regardless of whether people are buying the products or not.

I don't think that this argument can hold in the times of war. The responsibility for allowing this masacre is shared. Watching someone committing a crime but doing nothing other than observing that makes one an accomplice.

If boycotting such companies is the only thing we can do having a chance to influence the taxes they pay, then we should do it. Silence speaks louder than words. And talk is cheap. If people want to actually make difference by showing they don't support the fascist regime, they should do exactly that. It's our only chance to save everyone.
If people are not motivated by the genocide committed in their name, why should we avoid motivating them with the only pressure mechanism we've got?

**Comment by iluuu1994** [comment] 2022-03-07 15:34
I understand your guys' frustration and I'm very sorry for what happening in the country that you call home. It's unimaginable what you must be going through and it's important to state that I'm not trying to downplay that.

> Your army and government is your moral responsibility

That seems easy when your government is not corrupt... Many of them are going to prison for protesting, many of them are trying, but it's not exactly easy to overthrow a dictator with no resources.

**Comment by zkochan** [comment] 2022-03-07 15:38
I completely agree that a company that has employees in Russia should be boycotted.

**Comment by vadimdemedes** [comment] 2022-03-07 17:17
I don't know anything about JetBrains, but I want to drop my 2 cents on the direction of this discussion overall, because these arguments are quite popular these days.

> That seems easy when your government is not corrupt... Many of them are going to prison for protesting, many of them are trying, but it's not exactly easy to overthrow a dictator with no resources.

They've had 20 years to say something, let's stop making excuses for them. There are almost 12 million people living in moscow now and only a few thousand walked out yesterday. We've got people in small towns walking towards tanks with no weapons, I'd argue that's scarier than police.

> But I don't believe that even if we stopped buying every product of every company on that list it would make a measurable different to Putin.

You are right about that, no question about it. He doesn't give a shit about wellbeing of his nation, everyone except russians seem to know that. So we're counting on "regular" russians to feel discomfort and dissatisfaction with their living conditions, because that's the only way they will change their mind.

> They also have employees located in the Ukraine.

Also, it's Ukraine, not the Ukraine.

**Comment by webknjaz** [comment] 2022-03-07 17:37
> That seems easy when your government is not corrupt... Many of them are going to prison for protesting, many of them are trying, but it's not exactly easy to overthrow a dictator with no resources.

Nobody claimed it was easy. I can only point out that it is possible to learn how to stand up to to a bully dictator. Our compatriots stand unarmed against the fascist tanks, under the bullets. Don't tell me it's easier. Don't tell me that just because the dictator is bad, the people doing nothing are victims. My whole family fled from the hometown toward the village with my grandparents — they now live surrounded by explosions caused by the russian nazi army, my dad was sending me pictures of the russian missiles in the sky above them. At least some so the people in this issue, right here, have lost their house to a russian missile. It's not happening in some abstract far-away places of the country, it's happening at our homes. Is getting sanctioned worse than getting murdered?

As for learning to protest — people should learn to stand up for each other, not to allow the regime to drag others away. The failures can be prevented by uniting. Watch [Winter on Fire](https://www.netflix.com/title/80031666) for inspiration at least.

**Comment by iluuu1994** [comment] 2022-03-07 18:24
I'm sorry for what's happening to you and your family. Again, it was never my intention to downplay these horrific events. I don't think there's anything I can say at this point without coming off as insensitive. Thanks for your consideration.

**Comment by vshymanskyy** [comment] 2022-03-08 19:39
We decided not to remove JetBrains from the blacklist.

Check out also this:
![image](https://user-images.githubusercontent.com/1506708/157312368-0caf9d46-57db-4d7e-8cf0-cda2386738c3.png)

**Comment by vshymanskyy** [comment] 2022-03-11 15:12
Removed after #27

**Closed by vshymanskyy** 2022-03-11 15:12 UTC
Labels: resolved
